v0=float(input("Entre com o valor de v0:"))
a=float(input("Entre com o valor de a:"))
t=float(input("Entre com o valor de t:"))
s0=float(input("Entre com o valor de s0:"))
B=float(input("Entre com o valor de B:"))
b=float(input("Entre com o valor de b:"))
h=float(input("Entre com o valor de h:"))
print("O valor de s é", s0 + v0*t + (1/2)*a*t**2)
print("O valor de v  é", v0 + a*t)
print("O valor de B é", ((B + b)*h)/2)
